socialnetwork/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from socialnetwork.views import register,profile,otherProfile,addPost,timeline,about,settings,follow,following,unfollow,photo,addComment,refreshGlobal,confirm_registration


urlpatterns = [
    url(r'^login$', auth_views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout$', auth_views.logout_then_login, name='logout'),
    url(r'^register$', register, name='register'),
    url(r'^follow$', follow, name='follow'),
    url(r'^unfollow$', unfollow, name='unfollow'),
    url(r'^timeline/', timeline, name="timeline"),
    url(r'^following/', following, name="following"),
    url(r'^profile/', profile, name="profile"),
    url(r'^settings/', settings, name="settings"),
    url(r'^addPost/', addPost, name="addPost"),
    url(r'^addComment/', addComment, name="addComment"),
    url(r'^about/', about, name="about"),
    url(r'^refreshGlobal/', refreshGlobal, name="refreshGlobal"),
    url(r'^(?P<username>[^/]+)/$', otherProfile, name='otherProfile'),
    url(r'^photo/(?P<id>\d+)$', photo, name="photo"),
     url(r'^confirm-registration/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$',
        confirm_registration, name='confirm'),
    url(r'^', profile),
]

webapps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^socialnetwork/', include('socialnetwork.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('socialnetwork.urls')),
]

socialnetwork/models.py
from __future__ import unicode_literals
from datetime import datetime    
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Profile(models.Model):
	user = models.OneToOneField(User)
	bio = models.CharField(max_length=430,blank=True)
	age = models.IntegerField(default=0,blank=True)
	following = models.ManyToManyField('self',symmetrical=False)
	profile_picture = models.FileField(upload_to="socialnetwork/media/photos", blank=True)

	def __unicode__(self):
		return self.user.username

class Post(models.Model):
	user = models.ForeignKey(Profile)
	userId = models.IntegerField(default=0,blank=True)
	content = models.CharField(max_length=500) 
	date  = models.DateField()
	time = models.TimeField()
	public = models.BooleanField()
	username = models.CharField(max_length=20,blank=True)

	def __unicode__(self):
		return self.content

class Comment(models.Model):
	author 		= models.ForeignKey(Profile)
	post 		= models.ForeignKey(Post)
	body 		= models.CharField(max_length=256)
	datetime 	= models.DateTimeField()

socialnetwork/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget 
from django.contrib.auth.models import User
from django.core.validators import validate_email
from models import *

import re


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length = 20, widget=forms.TextInput(attrs={'placeholder': ' username'}))
    first_name = forms.CharField(max_length = 20, widget=forms.TextInput(attrs={'placeholder': ' first name'}))
    last_name = forms.CharField(max_length = 20, widget=forms.TextInput(attrs={'placeholder': ' last name'}))
    email = forms.CharField(max_length = 40, validators = [validate_email], widget=forms.TextInput(attrs={'placeholder': ' email'}))
    password1 = forms.CharField(max_length = 200, label='Password', widget = forms.PasswordInput(attrs={'placeholder': ' password'}))
    password2 = forms.CharField(max_length = 200, label='Confirm password', widget = forms.PasswordInput(attrs={'placeholder': ' confirm password'}))


    # Customizes form validation for properties that apply to more
    # than one field.  Overrides the forms.Form.clean function.
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super(RegistrationForm, self).clean()

        # Confirms that the two password fields match
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords did not match.")

        # Generally return the cleaned data we got from our parent.
        return cleaned_data


    # Customizes form validation for the username field.
    def clean_username(self):
        # Confirms that the username is not already present in the
        # User model database.
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__exact=username):
            raise forms.ValidationError("Username is already taken.")

        # Generally return the cleaned data we got from the cleaned_data
        # dictionary
        return username	


class PostForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'maxlength':512,'rows':3,'style':'resize:none;','class':'form-control'}))
    # body = forms.CharField(required=False, label="", widget=forms.Textarea(attrs={'maxlength':0,'rows':1,'style':'visibility:hidden;','class':'form-control'}))
    public = forms.BooleanField(required=False,label="private", widget=forms.CheckboxInput(attrs={'text':'Private'}))
    class Meta:
        model = Post
        exclude = (
            'user',
            'userId',
            'date',
            'time',
            'username',
        )


class SettingsForm(forms.Form):
    profile_picture = forms.FileField(required=False)
    first_name = forms.CharField(max_length = 20, widget=forms.TextInput(attrs={'placeholder': ' first name'}),required=False)
    last_name = forms.CharField(max_length = 20, widget=forms.TextInput(attrs={'placeholder': ' last name'}),required=False)
    bio = forms.CharField(label="", widget=forms.Textarea(attrs={'maxlength':430,'rows':3,'style':'resize:none;','class':'form-control'}),required=False)
    birthday = forms.CharField(max_length=10,required=False)
    new_password1 = forms.CharField(max_length = 200, label='new_password1', widget = forms.PasswordInput(attrs={'placeholder': ' new password'}),required=False)
    new_password2 = forms.CharField(max_length = 200, label='new_password2', widget = forms.PasswordInput(attrs={'placeholder': ' confirm new password'}),required=False)
    old_password = forms.CharField(max_length = 200, label='old_password', widget = forms.PasswordInput(attrs={'placeholder': ' old password'}),required=False)

    # Customizes form validation for properties that apply to more
    # than one field.  Overrides the forms.Form.clean function.
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super(SettingsForm, self).clean()

        # Confirms that the two password fields match
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')
        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError("Passwords did not match.")

        # Generally return the cleaned data we got from our parent.
        return cleaned_data

        # Customizes form validation for the username field.
    def clean_birthday(self):
        # Confirms that the username is not already present in the
        # User model database.
        birthday = self.cleaned_data.get('birthday')

        if birthday and not re.match('^\d\d\d\d-\d\d-\d\d$', birthday):
            raise forms.ValidationError('Must be yyyy-mm-dd')

        # Generally return the cleaned data we got from the cleaned_data
        # dictionary
        return birthday 

   
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ('body', )
        widgets = {
            'body' : forms.Textarea(attrs={'rows':2,'style':'resize:none;'}),
        }

socialnetwork/templates/about.html
{% extends "base.html" %}

{% block content %}
    <div>

        <br><br><br><br>

        <img class="center-block" src="https://lh3.googleusercontent.com/VaY5cFvhNuVh5Eh_8RdDeePGcSujnC0T2TTz2zh8J2_HiHKdKWi0q0aDGOUcHYIsq6Ciezs0sYe1pt5uqN8r6jlXchJXIE2aSFS-ReSFLTGQVN_KkWnH5JpyG5HLG4hozXsuUvz9BWP8JL2AVA-1GooH5sWoA9wNJHwlJ8Z0q_Cjz-E91gpY8zVdOQ_WAi7Ft5A5kiO3F8fNHzbGBLQTO-O0Gm5A1C4PsL3RO55OpFlxENRyL5CTRxTHFOubZR4I912ecwXtq53VO8gyfpo1Lq9VXDUNLju6NGhf-9KdXhg8jGRF23R5aX-OzU-VteDa34JLly6RFj6Wfu9C5N_gFf12oP6Zqt1Antkk7x_JAPRydRQauv-Fmz-8mgBDmitgpKpIRDCLiECDEDMysfbPKWnq7Ku7I6gkjYBuLekxGDenyKVaVPAv61iClTjJ1P_ROh1KtslQwn51HAaGh4MU2eeCky2kUu9xgvlBJgWr7-0Cf_Pj66d8etJywDgKeDovmduT0RxXVP3fZY7KQiYF74KmbSVXHo-wqUZd3Xc5IvVBwJz9YKaEvfBeULmhlwf-S3Y=w589-h192-no" alt="...">

    </div>
{% endblock %}

socialnetwork/templates/authBase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Social Network</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/authStyle.css" />
    <link href="//fonts.googleapis.com/css?family=Lato:100,300" rel="stylesheet" type="text/css">
</head>
<body>
    <div class="container">
        <div class="content">
            <div class="title"> The Social Network </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

socialnetwork/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Social Network</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/style.css" />
    <link href="//fonts.googleapis.com/css?family=Lato:100,300" rel="stylesheet" type="text/css">
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src="/static/js/socialnetwork.js" type="text/javascript"></script>
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'about' %}">The Social Network</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'following' %}">Following</a></li>
              <li><a href="{% url 'timeline' %}">Global</a></li>
              <li><a href="{% url 'profile' %}">Profile</a></li>
              <li><a href="{% url 'settings' %}">Settings</a></li>
              <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out" style="padding-right:0.5em"></span></a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    {% block content %}{% endblock %}
</body>
</html>

socialnetwork/templates/confirmed.html
{% extends "authBase.html" %}

{% block content %}
    <div class="container">

		<br>
		<div class="col-md-4 col-md-offset-4">
			<h3>Thank you for confirming your email address.
			Please click <a href="{% url 'login' %}">here</a> to login.
		</div>
    </div>
{% endblock %}

socialnetwork/templates/login.html
{% extends "authBase.html" %}

{% block content %}
    <div class="container">

        <br>

        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <h2>Login</h2>
            </div>
        </div>



        <form method="POST" action="{% url 'django.contrib.auth.views.login' %}">

             <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <input id="id_username" maxlength="254" name="username" type="text" placeholder=" username"/>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <input id="id_password" name="password" type="password" placeholder=" password"/>
                </div>
            </div>

            {% csrf_token %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <input type="submit" class="btn" style="background-color: White; border: 1px solid black">
                    <input type="hidden" name="next" value="{{ profileURL }}" />
                </div>
            </div>
        </form>

        <br>

        <form method="GET" action="{% url 'register' %}">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <input id="registerBtn" type="submit" value="Register">
                </div>
            </div>
        </form>

    </div>
{% endblock %}

socialnetwork/templates/needs-confirmation.html
{% extends "authBase.html" %}

{% block content %}
    <div class="container">

    	<br>
		<div class="col-md-4 col-md-offset-4">
			A confirmation email has been sent to {{email}}.  Please click the link
			in that email to confirm your email address and complete your registation.	    
		</div>
    </div>
{% endblock %}

socialnetwork/templates/profile.html
{% extends "base.html" %}

{% block content %}
    <div>

        <br><br>

        <div class="container-fluid text-center">
            {% if not user_profile.profile_picture %}
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                    </div>
                </div>
            {% endif %}
            {% if user_profile.profile_picture %}
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <img src="{% url 'photo' user_profile.id %}" class="img-circle" width="150" height="150">
                    </div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <h3>{{ user_profile.user.first_name }} {{ user_profile.user.last_name }}</h3>
                </div>
            </div>
            {%if user_profile.age > 0 %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <h5>Age: {{ user_profile.age}} </h5>
                </div>
            </div><br>
            {% endif %}
            {% if following and not myself %}
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <form method="POST" action="{% url 'follow' %}">
                            {% csrf_token %}
                            <input type="hidden" name="username" value="{{user_profile.user.username}}">
                            <button type="submit" class="btn btn-success btn-xs">Follow</button>
                        </form>
                    </div>
                </div>
            {% endif %}
            {% if notfollowing %}
                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <form method="POST" action="{% url 'unfollow' %}">
                            {% csrf_token %}
                            <input type="hidden" name="username" value="{{user_profile.user.username}}">
                            <button type="submit" class="btn btn-warning btn-xs">Unfollow</button>
                        </form>
                    </div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <p style="text-align: left">{{ user_profile.bio }}</p>
                </div>
            </div>
        </div>

        <br>

        <div class = "row">
            <div class="col-md-4 col-md-offset-4">
                    <form method="POST" action="{% url 'addPost' %}">
                        <div class="form-group">
                            {% if post_form %}
                                {% for field in post_form %}
                                    {{ field.label }} {{ field }}
                                {% endfor %}
                                <br>
                                {% csrf_token %}
                                <button type="submit" class="btn btn-xs pull-right btn-publish-post">Post</button>
                            {%  endif %}
                        </div>
                    </form>
            </div>
        </div>

        <br><br>

		<div class="feed-container">
            {% for post in posts %}
                <div class="panel-body post postContainer" postId="{{ post.id }}">
                    <div class="media">
                        <div class="col-md-4 col-md-offset-4">
                            <div class="panel panel-default">
                                <div class="panel-heading">{{post.time}} | {{ post.date }}</div>
                                <div class="panel-body">{{ post.content }}</div>
                                <div class="commentSection">
                                    <div class="commentsThread">
                                        {% for comment in post.comment_set.all %}
                                            <div class="panel-footer">
                                                {% if not comment.author.profile_picture %}
                                                    <div class="panel-heading"> <img src="https://lh3.googleusercontent.com/A9hkkCY0cXfwQL4LdNktOBIMSjC9o2_VwF1ShjN-oxpDHcI5Lz1BqhdZ0adS_28FCtJBdx5CDuO3pIZoeUS7_Mbrq_bU1UC7B2X8uV-XDTxazBMvM3cZBV9Np5oKiMODuKgK_WEyowhgSo6n8Xun6PxevnS8_UXa5B7YKVzRZrbq-PzSTJVuAq6FzhKcOXcvJ5gGi2EOAHFg1Ygxte3Ehz799_5Indk9tz8-9zWlVkbYgLEpXV72vKfOU2UuHjMu1xXQ0H-ZJAO4CYgJHcJtTKRC3oXMUivMs4GgEs3PTibdj6wsYjHIUkSgQiHnPcQEZC2QM_xzC9_ZnYVIaOF1q73tFWlUJs3SgbaDzzf0zI17cxQEUfmT9f12w9KbpeznPd_1xS2mbKxLQOGtjRngxecDw-M3zrZez-gMoiIV9I-iiywBs4SVbWFI9B8At3qWysk6CuYsRVI8rJQz68V1fN2k2_zjwTROF5mjqy9TpN6j5cRi-5XzpETvIgTbp6OBj2F0jZgcA_ACdTcuWUpY6s8qp1X3d4eLUclz-f9bIpbNgJpy-eCZrqDARX8ceE1hCLg=s636-no" alt="..." class="img-rounded" width="40" height="40">
                                                    <a href="{% url 'otherProfile' comment.author.user.username %}">  {{ comment.author.user.username }}</a> <p class="pull-right">{{comment.datetime}}</p></div>
                                                {% endif %}
                                                {% if comment.author.profile_picture %}
                                                    <div class="panel-heading"><img src="{% url 'photo' comment.author.id %}" class="img-rounded" width="40" height="40">
                                                    <a href="{% url 'otherProfile' comment.author.user.username %}">{{ comment.author.user.username }}</a> <p class="pull-right">{{comment.datetime}}</p></div>
                                                {% endif %}
                                                {{ comment.body }}
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="panel-footer">
                                        <div class="commentInput">
                                            <div class="media-body">
                                                {% for field in comment_form %}
                                                    {{ field }}
                                                {% endfor %}                                                
                                                <button class="btn btn-default btn-xs commentBtn">Comment</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            {% endfor %}
		</div>

    </div>
{% endblock %}

socialnetwork/templates/register.html
{% extends "authBase.html" %}

{% block content %}
    <div class="container">

        <br>

        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <h2>Register</h2>
            </div>
        </div>

        <form method="POST" action="{% url 'register' %}">
            {% for field in form %}
                {% if field.errors %}
                    <div class="row">
                        <div class="col-md-4 col-md-offset-4">
							{#{{ field.errors }}#}
                            <br>
                            <p>Error. Please enter again.</p>
                        </div>
		            </div>
                {% endif %}

                <div class="row">
			        <div class="col-md-4 col-md-offset-4">
                        {{ field }}
                    </div>
		        </div>

            {% endfor %}

            {% csrf_token %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <input type="submit" class="btn" style="background-color: White; border: 1px solid black">
                </div>
            </div>
        </form>
        <br>
        {% csrf_token %}
        <form method="GET" action="{% url 'login' %}">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <input id="registerBtn" type="submit" value="Login">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

socialnetwork/templates/settings.html
{% extends "base.html" %}

{% block content %}
    <div>

        <br><br>

        <div class="container-fluid text-center">

            <br>

            <form enctype="multipart/form-data" method="POST" action="{% url 'settings' %}">

                <div class="col-md-1 col-md-offset-5">
                    <input id="id_picture" name="profile_picture" type="file"></input>
                </div>

                <br><br>

                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <input id="id_first_name" maxlength="20" name="first_name" placeholder=" first name" type="text" /> 
                        <br><br>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <input id="id_last_name" maxlength="20" name="last_name" placeholder=" last name" type="text" /> 
                        <br><br>
                    </div>
                </div>        

                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <input id="id_new_password1" maxlength="200" name="new_password1" placeholder=" new password" type="password" /> 
                        <br><br>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <input id="id_new_password2" maxlength="200" name="new_password2" placeholder=" confirm new password" type="password" /> 
                        <br><br>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <input id="id_old_password" maxlength="200" name="old_password" placeholder=" old password" type="password" /> 
                        <br><br>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <input id="id_old_password" maxlength="200" name="old_password" placeholder=" old password" type="password" /> 
                        <br><br>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <input id="id_birthday" maxlength="200" name="birthday" placeholder=" yyyy-mm-dd" type="text"/>
                        <br><br>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <textarea class="form-control" cols="40" id="id_bio" maxlength="430" name="bio" rows="3" style="resize:none;" placeholder="bio"></textarea>                        
                        <br><br>
                    </div>
                </div>

            {% csrf_token %}
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <input type="submit" class="btn" style="background-color: White; border: 1px solid black">
                </div>
            </div>

            </form>
        </div>

        <br><br><br>

    </div>
{% endblock %}

socialnetwork/templates/timeline.html
{% extends "base.html" %}

{% block content %}
    <div>

        <br><br>

		<div class="feed-container timelineBegin">
            {% for post in posts %}
                <div class="panel-body post postContainer" postId="{{ post.id }}">
                    <div class="media">
                        <div class="col-md-6 col-md-offset-3">
                            <div class="panel panel-default">
                                {% if not post.user.profile_picture %}
                                    <div class="panel-heading">
                                    <a href="{% url 'otherProfile' post.user.user.username %}">  {{ post.user.user.username }}</a> <p class="pull-right">{{post.time}} | {{ post.date }}</p></div>
                                    <div class="panel-body">{{ post.content }}</div>
                                {% endif %}
                                {% if post.user.profile_picture %}
                                    <div class="panel-heading"><img src="{% url 'photo' post.user.id %}" class="img-circle" width="50" height="50">
                                    <a href="{% url 'otherProfile' post.user.user.username %}">{{ post.user.user.username }}</a> <p class="pull-right">{{post.time}} | {{ post.date }}</p></div>
                                    <div class="panel-body">{{ post.content }}</div>
                                {% endif %}
                                <div class="commentSection">
                                    <div class="commentsThread">
                                        {% for comment in post.comment_set.all %}
                                            <div class="panel-footer">
                                                {% if not comment.author.profile_picture %}
                                                    <div class="panel-heading">
                                                    <a href="{% url 'otherProfile' comment.author.user.username %}">  {{ comment.author.user.username }}</a> <p class="pull-right">{{comment.datetime}}</p></div>
                                                {% endif %}
                                                {% if comment.author.profile_picture %}
                                                    <div class="panel-heading"><img src="{% url 'photo' comment.author.id %}" class="img-rounded" width="40" height="40">
                                                    <a href="{% url 'otherProfile' comment.author.user.username %}">{{ comment.author.user.username }}</a> <p class="pull-right">{{comment.datetime}}</p></div>
                                                {% endif %}
                                                {{ comment.body }}
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="panel-footer">
                                        <div class="commentInput">
                                            <div class="media-body">
                                                {% for field in comment_form %}
                                                    {{ field }}
                                                {% endfor %}     
                                                <br>                                           
                                                <button class="btn btn-default btn-xs commentBtn">Comment</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
		</div>

    </div>
{% endblock %}